### ISSUE TITLE
Font issue on the documentation website.

### ISSUE THREAD

**Issue by dino8890** [wagtail/sphinx-wagtail-theme#245] opened 2022-12-05 09:40 UTC
There is some kind of font/text issue on the Wagtail docs, see screenshot below:

![Screenshot from 2022-12-05 10-36-52](https://user-images.githubusercontent.com/17911579/205603900-9275288b-d898-4237-944c-e1471d30ba25.png)

Whitespace character ` ` is unusually wide, however HTML does not show anything out of the ordinary:

`<p>Multi-site is a Wagtail project configuration where c...`

**Comment by thibaudcolas** [comment] 2023-03-08 12:46
Hi @dino8890, could you share what fonts you have configured in Firefox, Chrome, and at the OS level? For Firefox in particular, do you have it enabled to allow pages to set their own custom fonts?

I can reproduce what you describe but only when forcing the page to render text using Noto Color Emoji. We have `sans-serif` in our font stack – the emoji fonts would normally only be used when attempting to display characters missing from the base latin fonts, so I’d suspect this is a browser bug or configuration issue we can’t do much about it.

**Comment by dino8890** [comment] 2023-03-08 14:16
Hello, by default both Firefox and Chrome use Clear Sans as default sans-serif font. Websites are allowed to use their font preferences in Firefox. Chrome renders docs with Noto Sans despite the default font being Clear Sans. I don't know how browser choose their fonts exactly, but it seems to me like it should use Clear Sans.

I do have Roboto font installed which is explicitly set as a preference in the sphinx theme, but it is not used in Firefox or Chrome. Seems to me like this is an issue with Firefox so I'll file bug report with my package provider.

Thank you all!

**Comment by thibaudcolas** [comment] 2023-03-09 10:24
👍 it’s indeed very strange. This is my understanding of how a font is picked from our stack, based on what you said:

- I’d expect `Noto Sans` to be your OS-level default font, which we reference in our font stack via `system-ui`.
- Roboto is _after_ that so would only be used for platforms that don’t support `system-ui`.
- Your browser-configured font (Clear Sans) would only apply if `sans-serif` was reached in the stack.

So back to Firefox, I really don’t see how it’d reach the very end of the font stack, and why that’d be specific to `docs.wagtail.org`.

**Comment by laymonage** [comment] 2024-10-28 11:52
Since it's been over a year and we haven't been able to replicate this, I'm closing this. Feel free to reopen if this issue still persists.

**Closed by laymonage** 2024-10-28 11:52 UTC
Labels: documentation
